services:
  api:
    build:
      context: ./backend/Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Host=db
      - Database__Port=5432
      - Database__Name=roboteasy
      - Database__User=roboteasy
      - Database__Password=roboteasy123
      - AppSettings__JwtSecret=eBs3Cr78JSHE8XhbjeyMytn2zODSsd9k
      - AppSettings__JwtExpirationHours=8
      - Argon2__MemorySize=65536
      - Argon2__Iterations=4
      - Argon2__Parallelism=2
      - Argon2__HashLength=32
      - Argon2__SaltLength=16
      - GitHub__ClientId=SEU_CLIENT_ID_AQUI
      - GitHub__ClientSecret=SEU_CLIENT_SECRET_AQUI
      - GitHub__CallbackUrl=http://localhost:8080/api/v1/open/github/callback
      - AppSettings__CorsOrigins=*
      # http://localhost:5173,http://localhost:3000 CORS 
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: roboteasy
      POSTGRES_PASSWORD: roboteasy123
      POSTGRES_DB: roboteasy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roboteasy -d roboteasy"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
